=== Sleepw4lker/OcspManager/Config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="Config" type="ConfigType"/>    

    <xsd:complexType name="ConfigType">
        <xsd:sequence>
            <xsd:element name="CsrPath" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="CerPath" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="CaCerPath" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="RevocationConfig" type="RevocationConfigType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="RevocationConfigType">
    	<xsd:sequence>
            <xsd:element name="Name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="Type" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[Oo][Nn][Ll][Ii][Nn][Ee]"/>
                        <xsd:pattern value="[Oo][Ff][Ff][Ll][Ii][Nn][Ee]"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
    		<xsd:element name="CaCertFile" type="xsd:string" minOccurs="1" maxOccurs="1"/>
    		<xsd:element name="ConfigString" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="CertificateTemplate" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="KspName" minOccurs="0" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[Mm][Ii][Cc][Rr][Oo][Ss][Oo][Ff][Tt] [Ss][Oo][Ff][Tt][Ww][Aa][Rr][Ee] [Kk][Ee][Yy] [Ss][Tt][Oo][Rr][Aa][Gg][Ee] [Pp][Rr][Oo][Vv][Ii][Dd][Ee][Rr]"/>
                        <xsd:pattern value="[Uu][Tt][Ii][Mm][Aa][Cc][Oo] [Cc][Rr][Yy][Pp][Tt][Oo][Ss][Ee][Rr][Vv][Ee][Rr] [Kk][Ee][Yy] [Ss][Tt][Oo][Rr][Aa][Gg][Ee] [Pp][Rr][Oo][Vv][Ii][Dd][Ee][Rr]"/>
                        <xsd:pattern value="[Ss][Aa][Ff][Ee][Nn][Ee][Tt] [Kk][Ee][Yy] [Ss][Tt][Oo][Rr][Aa][Gg][Ee] [Pp][Rr][Oo][Vv][Ii][Dd][Ee][Rr]"/>
                        <xsd:pattern value="[Nn][Cc][Ii][Pp][Hh][Ee][Rr] [Ss][Ee][Cc][Uu][Rr][Ii][Tt][Yy] [Ww][Oo][Rr][Ll][Dd] [Kk][Ee][Yy] [Ss][Tt][Oo][Rr][Aa][Gg][Ee] [Pp][Rr][Oo][Vv][Ii][Dd][Ee][Rr]"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="KeyLength" minOccurs="0" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:enumeration value="4096"/>
                        <xsd:enumeration value="3072"/>
                        <xsd:enumeration value="2048"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="SignatureHashAlgorithm" minOccurs="1" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[Ss][Hh][Aa]1"/>
                        <xsd:pattern value="[Ss][Hh][Aa]256"/>
                        <xsd:pattern value="[Ss][Hh][Aa]384"/>
                        <xsd:pattern value="[Ss][Hh][Aa]512"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
    		<xsd:element name="Cdp" type="xsd:string" minOccurs="1" maxOccurs="10"/>
    		<xsd:element name="DeltaCdp" type="xsd:string" minOccurs="0" maxOccurs="10"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Sleepw4lker/OcspManager/Config.xml
<?xml version="1.0"?>

<Config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Config.xsd">
    <CsrPath>C:\Scripts\ManualOcspConfiguration\csr</CsrPath>
    <CerPath>C:\Scripts\ManualOcspConfiguration\cer</CerPath>
    <CaCerPath>C:\WebSites\pki.fabrikam.com\CertData</CaCerPath>
    <KeyLength>2048</KeyLength>
    <KspName>Utimaco CryptoServer Key Storage Provider</KspName>
    <RevocationConfig>
        <CaCertFile>Fabrikam Issuing CA 1.crt</CaCertFile>
        <ConfigString>adcsca02.corp.fabrikam.com\Fabrikam Issuing CA 1</ConfigString>
        <TemplateName>FabrikamOCSPDMZ</TemplateName>
        <Cdp>ldap:///CN=Fabrikam%20Issuing%20CA%201,CN=Fabrikam%20Issuing%20CA%201,CN=CDP,CN=Public%20Key%20Services,CN=Services,CN=Configuration,DC=corp,DC=fabrikam,DC=com?certificateRevocationList?base?objectClass=cRLDistributionPoint</Cdp>
        <Cdp>http://pki.fabrikam.com/CertData/Fabrikam%20Issuing%20CA%201.crl</Cdp>
    </RevocationConfig>
    <RevocationConfig>
        <CaCertFile>Fabrikam Issuing CA 2.crt</CaCertFile>
        <ConfigString>adcsca03.corp.fabrikam.com\Fabrikam Issuing CA 2</ConfigString>
        <TemplateName>FabrikamOCSPDMZ</TemplateName>
        <Cdp>ldap:///CN=Fabrikam%20Issuing%20CA%202,CN=Fabrikam%20Issuing%20CA%202,CN=CDP,CN=Public%20Key%20Services,CN=Services,CN=Configuration,DC=corp,DC=fabrikam,DC=com?certificateRevocationList?base?objectClass=cRLDistributionPoint</Cdp>
        <Cdp>http://pki.fabrikam.com/CertData/Fabrikam%20Issuing%20CA%202.crl</Cdp>
    </RevocationConfig>
</Config>
